import { useEffect, useState } from 'react'
import type { Category, MigrationReview, Note, Subcategory } from '../../shared/contracts'
import { CategoryPicker } from './CategoryPicker'
import { resultValue } from '../apiResult'
export function MigrationReviewPanel({categories,subcategories,onOpen,onChanged}:{categories:Category[];subcategories:Subcategory[];onOpen:(id:string,deleted:boolean)=>void;onChanged:()=>void}) {
  const [rows,setRows]=useState<(MigrationReview&{item:Note})[]>([])
  const [error,setError]=useState(''),[includeTrash,setIncludeTrash]=useState(false)
  useEffect(()=>{let active=true;void window.captured.notes.migrationReview().then(async result=>{const reports=resultValue(result);const loaded=await Promise.all(reports.map(async row=>{const item=resultValue(await window.captured.notes.get(row.noteId));return item?{...row,item}:null}));if(active)setRows(loaded.filter(row=>row!==null).filter(row=>row.item.kind!=='note'))}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:'Review could not be loaded.')});return()=>{active=false}},[])
  return <section className="migration-review"><h1>Review subcategories</h1><p>Existing tags were preserved. These items had overlapping labels or labels from another category. Choose one subcategory, or keep the item without one.</p><label><input type="checkbox" checked={includeTrash} onChange={event=>setIncludeTrash(event.target.checked)}/> Include Trash</label>{error&&<div role="alert" className="inline-error">{error}</div>}
    {!rows.length&&<p>No assignments need review.</p>}{rows.filter(row=>includeTrash||row.item.deletedAt===null).map(row=><ReviewRow key={row.noteId} row={row} categories={categories} subcategories={subcategories} onOpen={()=>onOpen(row.noteId,row.item.deletedAt!==null)} onResolve={async(categoryId,subcategoryId)=>{try{resultValue(await window.captured.notes.resolveMigrationReview({id:row.noteId,expectedRevision:row.item.revision,categoryId,subcategoryId}));setRows(current=>current.filter(item=>item.noteId!==row.noteId));onChanged()}catch(reason){setError(reason instanceof Error?reason.message:'Could not save assignment. Reload the review if this item changed elsewhere.')}}}/>)}</section>
}
function ReviewRow({row,categories,subcategories,onOpen,onResolve}:{row:MigrationReview&{item:Note};categories:Category[];subcategories:Subcategory[];onOpen:()=>void;onResolve:(categoryId:string|null,subcategoryId:string|null)=>Promise<void>}) {
  const [categoryId,setCategoryId]=useState(row.item.categoryId),[subcategoryId,setSubcategoryId]=useState(row.item.subcategoryId??null),[busy,setBusy]=useState(false)
  const candidates=row.candidates.map(id=>subcategories.find(item=>item.id===id)).filter(item=>item!==undefined)
  return <article className="migration-review-row"><button className="review-item-title" onClick={onOpen}>{row.item.body||'Image item'}{row.item.deletedAt!==null?' · In Trash':''}</button><div className="muted">{row.item.tags.map(tag=>`#${tag}`).join(' ')}<br/>Possible subcategories: {candidates.map(item=>`${categories.find(category=>category.id===item.categoryId)?.name??''} / ${item.name}`).join(', ')||'None remaining'}</div>{row.item.deletedAt!==null?<p>Restore this item to edit its assignment.</p>:<><CategoryPicker categories={categories} subcategories={subcategories} categoryId={categoryId} subcategoryId={subcategoryId} onChange={(category,subcategory)=>{setCategoryId(category);setSubcategoryId(subcategory)}} disabled={busy}/><button className="button secondary small" disabled={busy} onClick={()=>{setBusy(true);void onResolve(categoryId,subcategoryId).finally(()=>setBusy(false))}}>{subcategoryId?'Save assignment':'Keep without subcategory'}</button></>}</article>
}
