import { ColorPalette } from './ColorPalette'
import { useRef, useState } from 'react'
import { ChevronDown, ChevronRight, Folder, Hash, Plus, Trash2, Pencil, ArrowUp, ArrowDown } from 'lucide-react'
import type { Category, Subcategory, TagRecord } from '../../shared/contracts'
import { resultValue } from '../apiResult'
import { Dialog, DialogContent, DialogTitle } from './ui/dialog'
export function TaxonomyNav({categories,subcategories,tags,onCategory,onSubcategory,onTag,onChanged,onError,activeCategory,activeSubcategory,activeTag}: {categories:Category[];subcategories:Subcategory[];tags:TagRecord[];onCategory:(item:Category)=>void;onSubcategory:(item:Subcategory)=>void;onTag:(item:TagRecord)=>void;onChanged:()=>void;onError:(message:string)=>void;activeCategory:string|null;activeSubcategory:string|null;activeTag:string|null}) {
  const drag=useRef<{kind:'category'|'subcategory'|'tag';id:string;categoryId?:string}|null>(null)
  const [closed,setClosed]=useState<Record<string,boolean>>({})
  const [adding,setAdding]=useState<string|null>(null)
  const [name,setName]=useState('')
  const [rename,setRename]=useState<{kind:'category'|'subcategory'|'tag';id:string;name:string;color?:string}|null>(null)
  const [busy,setBusy]=useState(false)
  async function run(action:()=>Promise<unknown>) { if(busy)return; setBusy(true); try{await action();onChanged()}catch(reason){onError(reason instanceof Error?reason.message:'Could not save taxonomy.')}finally{setBusy(false)} }
  async function add(){if(!adding)return;await run(async()=>{if(adding==='category')resultValue(await window.captured.notes.createCategory(name));else if(adding==='tag')resultValue(await window.captured.notes.createTag({name}));else resultValue(await window.captured.notes.createSubcategory({name,categoryId:adding}));setAdding(null);setName('')})}
  function move(kind:'category'|'subcategory'|'tag',id:string,direction:number,categoryId?:string){const group=kind==='category'?categories:kind==='tag'?tags:subcategories.filter(item=>item.categoryId===categoryId);const ids=group.map(item=>item.id),index=ids.indexOf(id),target=index+direction;if(target<0||target>=ids.length)return;[ids[index],ids[target]]=[ids[target]!,ids[index]!];void run(async()=>resultValue(await(kind==='category'?window.captured.notes.reorderCategories({ids}):kind==='tag'?window.captured.notes.reorderTags({categoryId:null,ids}):window.captured.notes.reorderSubcategories({categoryId:categoryId!,ids}))))}
  function dragProps(kind:'category'|'subcategory'|'tag',id:string,categoryId?:string) {
    return {draggable:!busy,onDragStart:(event:React.DragEvent)=>{drag.current={kind,id,categoryId};event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',id);event.stopPropagation()},onDragEnd:()=>{drag.current=null},onDragOver:(event:React.DragEvent)=>{if(drag.current?.kind===kind&&drag.current.categoryId===categoryId)event.preventDefault()},onDrop:(event:React.DragEvent)=>{event.preventDefault();event.stopPropagation();const active=drag.current;drag.current=null;if(!active||active.kind!==kind||active.categoryId!==categoryId||active.id===id)return;const group=kind==='category'?categories:kind==='tag'?tags:subcategories.filter(item=>item.categoryId===categoryId);const ids=group.map(item=>item.id),from=ids.indexOf(active.id),to=ids.indexOf(id);if(from<0||to<0)return;ids.splice(to,0,ids.splice(from,1)[0]!);void run(async()=>resultValue(await(kind==='category'?window.captured.notes.reorderCategories({ids}):kind==='tag'?window.captured.notes.reorderTags({categoryId:null,ids}):window.captured.notes.reorderSubcategories({categoryId:categoryId!,ids}))))}}
  }
  function controls(kind:'category'|'subcategory'|'tag',item:Category|Subcategory|TagRecord,categoryId?:string){return <span className="taxonomy-controls"><button disabled={busy} aria-label={`Edit ${kind} ${item.name}`} onClick={()=>setRename({kind,id:item.id,name:item.name,color:('color'in item?item.color:undefined)??'#85858e'})}><Pencil size={11}/></button><button disabled={busy} aria-label={`Move ${item.name} up`} onClick={()=>move(kind,item.id,-1,categoryId)}><ArrowUp size={11}/></button><button disabled={busy} aria-label={`Move ${item.name} down`} onClick={()=>move(kind,item.id,1,categoryId)}><ArrowDown size={11}/></button><button disabled={busy} aria-label={`Delete ${kind} ${item.name}`} onClick={()=>{if(!window.confirm(kind==='category'?`Delete category “${item.name}” and its subcategories? Items become unassigned; tags and images are preserved.`:kind==='subcategory'?`Delete subcategory “${item.name}”? Items stay in their category.`:`Delete tag “${item.name}” from all items?`))return;void run(async()=>resultValue(await(kind==='category'?window.captured.notes.deleteCategory(item.id):kind==='subcategory'?window.captured.notes.deleteSubcategory(item.id):window.captured.notes.deleteTag(item.id))))}}><Trash2 size={11}/></button></span>}
  const form=adding&&<form className="taxonomy-dialog-form" onSubmit={event=>{event.preventDefault();void add()}}><input autoFocus aria-label={adding==='category'?'New category name':adding==='tag'?'New tag name':'New subcategory name'} placeholder="Name" maxLength={adding==='category'?60:40} value={name} onChange={event=>setName(event.target.value)}/><div className="dialog-actions"><button disabled={busy} type="button" onClick={()=>setAdding(null)}>Cancel</button><button disabled={busy||!name.trim()} className="primary" type="submit">Add</button></div></form>
  return <div className="taxonomy-navigation">
    <div className="category-section-heading"><button aria-expanded={!closed.categories} onClick={()=>setClosed({...closed,categories:!closed.categories})}>Categories {closed.categories?<ChevronRight size={13}/>:<ChevronDown size={13}/>}</button><button aria-label="Add category" onClick={()=>{setAdding('category');setName('')}}><Plus size={14}/></button></div>
    {!closed.categories&&categories.map(category=><div className="category-group" key={category.id}>
      <div className="taxonomy-nav-row" data-kind="category"><button aria-label={`${closed[category.id]?'Expand':'Collapse'} ${category.name}`} aria-expanded={!closed[category.id]} onClick={()=>setClosed({...closed,[category.id]:!closed[category.id]})}>{closed[category.id]?<ChevronRight size={12}/>:<ChevronDown size={12}/>}</button><button {...dragProps('category',category.id)} className={activeCategory===category.id&&!activeSubcategory?'active':''} onClick={()=>onCategory(category)}><Folder size={13} color={category.color}/><span className="taxonomy-name">{category.name}</span></button>{controls('category',category)}<button aria-label={`Add subcategory in ${category.name}`} onClick={()=>{setAdding(category.id);setName('');setClosed({...closed,[category.id]:false})}}><Plus size={12}/></button></div>
      {!closed[category.id]&&<div className="category-children">{subcategories.filter(item=>item.categoryId===category.id).map(item=><div className="taxonomy-nav-row" key={item.id}><button {...dragProps('subcategory',item.id,item.categoryId)} className={activeSubcategory===item.id?'active':''} onClick={()=>onSubcategory(item)}><Folder size={12} color={item.color}/><span className="taxonomy-name">{item.name}</span><small> {item.count||''}</small></button>{controls('subcategory',item,category.id)}</div>)}</div>}
    </div>)}
    <div className="category-section-heading"><button aria-expanded={!closed.tags} onClick={()=>setClosed({...closed,tags:!closed.tags})}>Tags {closed.tags?<ChevronRight size={13}/>:<ChevronDown size={13}/>}</button><button aria-label="Add tag" onClick={()=>{setAdding('tag');setName('')}}><Plus size={14}/></button></div>
    {!closed.tags&&tags.map(item=><div className="taxonomy-nav-row" key={item.id}><button {...dragProps('tag',item.id)} className={activeTag===item.id?'active':''} onClick={()=>onTag(item)}><Hash size={13} color={item.color}/><span className="taxonomy-name">{item.name}</span><small> {item.count||''}</small></button>{controls('tag',item)}</div>)}
<Dialog open={!!adding} onOpenChange={open=>{if(!open&&!busy)setAdding(null)}}><DialogContent className="taxonomy-dialog" showCloseButton={!busy}><DialogTitle>{adding==='category'?'Add category':adding==='tag'?'Add tag':'Add subcategory'}</DialogTitle>{form}</DialogContent></Dialog>
    <Dialog open={!!rename} onOpenChange={open=>{if(!open&&!busy)setRename(null)}}><DialogContent className="taxonomy-dialog" showCloseButton={!busy}><DialogTitle>Edit {rename?.kind}</DialogTitle>{rename&&<form className="taxonomy-dialog-form" onSubmit={event=>{event.preventDefault();void run(async()=>{resultValue<unknown>(await(rename.kind==='category'?window.captured.notes.updateCategory({id:rename.id,name:rename.name,color:rename.color}):rename.kind==='subcategory'?window.captured.notes.updateSubcategory({id:rename.id,name:rename.name,color:rename.color!}):window.captured.notes.updateTag({id:rename.id,name:rename.name,color:rename.color!,categoryId:null})));setRename(null)})}}><label>Name<input autoFocus aria-label="Rename taxonomy item" maxLength={rename.kind==='category'?60:40} value={rename.name} onChange={event=>setRename({...rename,name:event.target.value})}/></label>{rename.color&&<div className="taxonomy-color-field"><span>Color</span><ColorPalette value={rename.color} disabled={busy} onChange={color=>setRename({...rename,color})}/></div>}<div className="dialog-actions"><button disabled={busy} type="button" onClick={()=>setRename(null)}>Cancel</button><button className="primary" disabled={busy||!rename.name.trim()}>Save</button></div></form>}</DialogContent></Dialog>
  </div>
}
