const { app, BrowserWindow } = require('electron')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { pathToFileURL } = require('node:url')
const tempRoot = path.resolve(os.tmpdir())
const profile = fs.mkdtempSync(path.join(tempRoot, 'captured-taxonomy-smoke-'))
const output = path.resolve(__dirname, '../tests/.visual')
fs.mkdirSync(output, { recursive: true })
fs.writeFileSync(path.join(profile, 'settings.json'), JSON.stringify({ firstRunComplete: true, shortcutEnabled: false, closeToTray: false, captureProtection: false, theme: 'light' }))
app.setPath('userData', profile)
app.commandLine.appendSwitch('disable-gpu')
require('../out/main/index.js')
const wait = ms => new Promise(resolve => setTimeout(resolve, ms))
app.whenReady().then(async () => {
  let window
  for (let i=0;i<60;i++) {
    window=BrowserWindow.getAllWindows().find(win=>win.webContents.getURL().endsWith('/index.html'))
    if(window&&await window.webContents.executeJavaScript('Boolean(document.querySelector(".sidebar"))'))break
    await wait(100)
  }
  if(!window)throw Error('Notes window did not load')
  window.setSize(1400,800)
  window.webContents.setBackgroundThrottling(false)
  const evaluate=async code=>{try{return await window.webContents.executeJavaScript(code)}catch(error){throw Error(`${code}: ${error.message}`)}}
  const until=async code=>{for(let i=0;i<80;i++){if(await evaluate(code))return;await wait(100)}throw Error(`Timed out: ${code}: ${await evaluate("document.querySelector('main')?.textContent")}`)}
  const expandUnplanned=async()=>{await until(`Boolean(document.querySelector('.tasks-page'))`);await evaluate(`document.querySelector('.tasks-board > [data-horizon="unplanned"].is-collapsed .tasks-column-heading button')?.click()`)}
  const errors=[]
  window.webContents.on('console-message',event=>{if(event.level==='error')errors.push(event.message)})
  const seeded=await evaluate(`(async()=>{
    const category=await window.captured.notes.createCategory('Work');if(!category.ok)throw Error(category.message);
    const other=await window.captured.notes.createCategory('Personal');
    const sub=await window.captured.notes.createSubcategory({name:'Project Alpha',categoryId:category.value.id});if(!sub.ok)throw Error(sub.message);
    const task=await window.captured.planner.createTask({body:'Screenshot context',categoryId:category.value.id,subcategoryId:sub.value.id,tags:['waiting','follow-up'],placement:{kind:'backlog'}});if(!task.ok)throw Error(task.message);
    return {category:category.value,other:other.value,sub:sub.value,task:task.value};
  })()`)
  await wait(350)
  await evaluate(`[...document.querySelectorAll('.note-row-open')].find(button=>button.textContent.includes('Screenshot context')).click()`)
  await wait(200)
  await wait(150)
  await evaluate(`(()=>{
    const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl8n+QAAAAASUVORK5CYII=';
    const bytes=Uint8Array.from(atob(png),value=>value.charCodeAt(0));
    const transfer=new DataTransfer();transfer.items.add(new File([bytes],'snip.png',{type:'image/png'}));
    document.querySelector('.task-detail-editor').dispatchEvent(new ClipboardEvent('paste',{clipboardData:transfer,bubbles:true,cancelable:true}));
  })()`)
  await wait(200)
  assert.equal(await evaluate(`document.querySelectorAll('.attachment-thumbnail').length`),1)
  const screenshot=async (name,width=1180,height=800)=>{
    const html=await evaluate(`(()=>{const clone=document.documentElement.cloneNode(true);const selects=clone.querySelectorAll('select');document.querySelectorAll('select').forEach((live,index)=>{[...selects[index].options].forEach((option,position)=>{if(live.options[position].selected)option.setAttribute('selected','selected');else option.removeAttribute('selected')})});const areas=clone.querySelectorAll('textarea');document.querySelectorAll('textarea').forEach((live,index)=>{areas[index].textContent=live.value});return clone.outerHTML})()` )
    const file=path.join(profile,'snapshot.html'),base=pathToFileURL(path.resolve(__dirname,'../out/renderer/index.html')).href
    fs.writeFileSync(file,html.replace('<head>',`<head><base href="${base}">`))
    const preview=new BrowserWindow({width,height,show:false,webPreferences:{offscreen:true,javascript:false}})
    try{await preview.loadFile(file);await wait(350);fs.writeFileSync(path.join(output,name),(await preview.webContents.capturePage()).toPNG())}finally{preview.destroy()}
  }
  await screenshot('taxonomy-editor-light.png')
  await evaluate(`[...document.querySelectorAll('button')].find(button=>button.textContent.trim()==='Save').click()`)
  await wait(200)
  let saved=await evaluate(`window.captured.notes.get(${JSON.stringify(seeded.task.id)})`)
  assert.equal(saved.ok,true);assert.equal(saved.value.images.length,1);assert.equal(saved.value.subcategoryId,seeded.sub.id);assert.deepEqual(new Set(saved.value.tags),new Set(['waiting','follow-up']))
  const image=await evaluate(`window.captured.notes.image(${JSON.stringify(saved.value.images[0].id)})`);assert.equal(image.ok,true)
  assert.equal(await evaluate(`document.querySelectorAll('.note-row input[type="checkbox"]').length`),1)
  await screenshot('taxonomy-all-items-light.png')
  await evaluate(`[...document.querySelectorAll('.side-nav button')].find(button=>button.textContent.trim().startsWith('Backlog')).click()`)
  await wait(300)
  await expandUnplanned()
  await until(`Boolean(document.querySelector('[aria-label="Filter tasks by category"]'))`)
  await until(`Boolean(document.querySelector('.tasks-card-body'))`)
  await screenshot('taxonomy-backlog-light.png')
  await evaluate(`document.querySelector('[aria-label="Tag filter for Tasks: All tags"]').click()`)
  await wait(250)
  await screenshot('taxonomy-tag-filter-light.png')
  await evaluate(`window.captured.settings.update({theme:'dark'})`)
  await wait(250)
  await screenshot('taxonomy-tag-filter-dark.png')
  await evaluate(`window.captured.settings.update({theme:'light'})`)
  await wait(150)
  await evaluate(`document.querySelector('[aria-label="Tag filter for Tasks: All tags"]').click()`)
  await wait(150)
  await evaluate(`[...document.querySelectorAll('.tasks-card-body')].find(button=>button.textContent.includes('Screenshot context')).click()`)
  await wait(200)
  assert.equal(await evaluate(`document.querySelector('[aria-label="Item subcategory"]').value`),seeded.sub.id)
  await evaluate(`(()=>{const select=document.querySelector('[aria-label="Item category"]');Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set.call(select,${JSON.stringify(seeded.other.id)});select.dispatchEvent(new Event('change',{bubbles:true}));})()`)
  await wait(100)
  assert.equal(await evaluate(`document.querySelector('[aria-label="Item subcategory"]').value`),'')
  await evaluate(`[...document.querySelectorAll('.task-detail-actions button')].find(button=>button.textContent.trim()==='Save').click()`)
  await wait(200)
  saved=await evaluate(`window.captured.notes.get(${JSON.stringify(seeded.task.id)})`)
  assert.equal(saved.value.categoryId,seeded.other.id);assert.equal(saved.value.subcategoryId,null);assert.equal(saved.value.images.length,1);assert.deepEqual(new Set(saved.value.tags),new Set(['waiting','follow-up']))
  await evaluate(`window.captured.notes.setCategory({id:${JSON.stringify(seeded.task.id)},categoryId:${JSON.stringify(seeded.category.id)},subcategoryId:${JSON.stringify(seeded.sub.id)}})`)
  await evaluate(`window.captured.planner.createTask({body:'Later screenshot follow-up',categoryId:${JSON.stringify(seeded.category.id)},tags:['follow-up'],placement:{kind:'later'}})`)
  await wait(300)
  await evaluate(`[...document.querySelectorAll('.side-nav button')].find(button=>button.textContent.trim()==='Tasks').click()`)
  await wait(300)
  await screenshot('taxonomy-later-light.png')
  await evaluate(`window.captured.windows.openCapture()`)
  await wait(250)
  const capture=BrowserWindow.getAllWindows().find(win=>win.webContents.getURL().endsWith('/capture.html'))
  assert.ok(capture)
  const draft=await capture.webContents.executeJavaScript(`window.captured.capture.updateDraft({body:'Draft with subcategory',generation:0,revision:1,categoryId:${JSON.stringify(seeded.category.id)},subcategoryId:${JSON.stringify(seeded.sub.id)}})`)
  assert.equal(draft.ok,true)
  const state=await capture.webContents.executeJavaScript('window.captured.capture.getState()')
  assert.equal(state.value.subcategoryId,seeded.sub.id)
  capture.hide();await wait(150)
  await window.reload();await wait(500)
  const persisted=await window.webContents.executeJavaScript(`window.captured.notes.get(${JSON.stringify(seeded.task.id)})`)
  assert.equal(persisted.value.subcategoryId,seeded.sub.id);assert.equal(persisted.value.images.length,1)
  await evaluate(`document.querySelector('[aria-label="Edit tag follow-up"]').click()`)
  await wait(200)
  assert.equal(await evaluate(`document.querySelectorAll('.color-palette button').length`),12)
  assert.equal(await evaluate(`document.querySelectorAll('input[type="color"]').length`),0)
  await evaluate(`document.querySelector('.color-palette [aria-label="Blue"]').click()`)
  await screenshot('taxonomy-palette-light.png')
  await evaluate(`document.querySelector('.taxonomy-dialog-form .primary').click()`)
  await wait(250)
  const paletteSaved=await evaluate(`window.captured.notes.taxonomy()`)
  assert.equal(paletteSaved.value.tags.find(tag=>tag.name==='follow-up').color,'#3b82f6')
  await capture.webContents.executeJavaScript(`(async()=>{const state=await window.captured.capture.getState();return window.captured.capture.submit({requestId:crypto.randomUUID(),generation:state.value.generation,body:'Unassigned inbox review',categoryId:null,subcategoryId:null,tags:[]})})()`)
  await evaluate(`[...document.querySelectorAll('.side-nav button')].find(button=>button.textContent.trim().startsWith('Backlog')).click()`)
  await wait(250)
  await expandUnplanned()
  await until(`Boolean([...document.querySelectorAll('.tasks-backlog-group .tasks-card-body')].find(button=>button.textContent.includes('Unassigned inbox review')))` )
  assert.equal(await evaluate(`Boolean([...document.querySelectorAll('.tasks-backlog-group .tasks-card-body')].find(button=>button.textContent.includes('Unassigned inbox review')))`),true)
  await screenshot('tasks-captures-light.png')
  await evaluate(`[...document.querySelectorAll('.tasks-backlog-group .tasks-card-body')].find(button=>button.textContent.includes('Unassigned inbox review')).click()`)
  await wait(150)
  await evaluate(`(()=>{const select=document.querySelector('[aria-label="Item category"]');Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set.call(select,${JSON.stringify(seeded.category.id)});select.dispatchEvent(new Event('change',{bubbles:true}));})()`)
  await wait(150)
  await screenshot('tasks-capture-category-light.png')
  await evaluate(`[...document.querySelectorAll('.task-detail-actions button')].find(button=>button.textContent.trim()==='Save').click()`)
  await wait(250)
  assert.equal(await evaluate(`document.querySelector('.tasks-backlog-groups').textContent.includes('Work')`),true)
  await evaluate(`window.captured.settings.update({theme:'dark'})`)
  await wait(150)
  await screenshot('inbox-compact-dark.png')
  window.setSize(1920,1080)
  await wait(150)
  await screenshot('inbox-compact-large-dark.png',1920,1080)
  window.setSize(760,800)
  await wait(150)
  await screenshot('inbox-compact-narrow-dark.png',760,800)
  assert.equal(errors.length,0,errors.join('\n'))
  process.stdout.write('taxonomy_ipc=ok note_image_paste=ok task_category_move=ok independent_tags=ok capture_draft=ok restart=ok screenshots=tests/.visual\n')
  app.exit(0)
}).catch(error=>{process.stderr.write(`${error.stack??error}\n`);app.exit(1)})
app.on('quit',()=>{const target=path.resolve(profile);if(path.dirname(target)!==tempRoot||!path.basename(target).startsWith('captured-taxonomy-smoke-'))return;try{fs.rmSync(target,{recursive:true,force:true})}catch{}})
